name: critalarm_face_example
description: Examples for the critalarm_face package.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.12.0

dependencies:
  critalarm_face:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0

flutter:
  uses-material-design: true
